### ISSUE TITLE
wzrd doesn't work well on windows

### ISSUE THREAD

**Issue by njam3** [Jam3/jam3-lesson-module-basics#2]
It requires browserify to be installed globally and locally to compile the javascript, sometimes that doesn't even fix it as it messes up the pathing. Is there another tool available?

**Comment by mattdesl** [comment]
Thanks

Here's another that uses watchify, but otherwise feels the same as wzrd:
https://github.com/mattdesl/budo

``` sh
npm install budo -g
```

Then: 

``` sh
budo index.js
```

Also there is Beefy:
https://github.com/chrisdickinson/beefy

I will check it out on a PC tomorrow and see if I can submit a PR to wzrd. It's the smallest/simplest of the bunch so I figured probably the best for a quick intro; but I could change the guide to use beefy or budo if it's still causing issues.

**Comment by njam3** [comment]
I'll give it a try as well tomorrow. If it works, we can just have a line saying if you are experiencing trouble with wzrd, give budo a try.
